[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Только WASM-выход

[dependencies]
yew.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
serde.workspace = true
gloo-net.workspace = true
web-sys.workspace = true