[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Веб-фреймворк
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true

# Tor интеграция
arti-client.workspace = true
tor-hsservice.workspace = true
# База данных
sqlx.workspace = true

# Сериализация
serde.workspace = true
serde_json.workspace = true

# Дополнительные утилиты
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true

# Добавляем для работы с UUID
uuid.workspace = true



chrono.workspace = true
