[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[[bin]]  # Добавьте эту секцию
name = "backend"
path = "src/main.rs"

[dependencies]
arti-client = { version = "0.10.2", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"