[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
sqlx.workspace = true

# Tor с минимальными фичами
arti-client = { workspace = true, default-features = false, features = ["tokio"] }