[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[features]
default = []
sqlx = ["dep:sqlx"]

[dependencies]
axum = "0.7"
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.17.0", features = ["serde", "v4"] }
tower-http = { version = "0.5", features = ["set-header"] }
thiserror = "1.0"
chrono = { version = "0.4.41", features = ["serde"] }
sqlx = { version = "0.8.6", optional = true }
tor-dirmgr = "0.10"
arti-client = "0.10"
rusqlite = "0.36.0"