[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Веб-фреймворк
axum = "0.8.4"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }

# Tor интеграция
arti-client = "0.31.0"
tor-hsservice = "0.31.0"
# База данных
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-native-tls"] }


# Сериализация
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"

# Дополнительные утилиты
anyhow = "1.0"
thiserror = "2.0.12"
log = "0.4"
env_logger = "0.11.8"

# Добавляем для работы с UUID
uuid = { version = "1.7.0", features = ["v4", "serde"] }



chrono = { version = "0.4.41", features = ["serde"] }