[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
# Заменяем на рабочую версию monero
monero-rpc = "0.4"  # Максимальная доступная версия

# Bitcoin - используем последнюю стабильную
bitcoin = { version = "0.32.6", features = ["serde"] }

# Общие зависимости
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
hex = "0.4"