[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "../backend" }
sqlx = { workspace = true, features = ["postgres"] }
bitcoin = { workspace = true, features = ["std"] }  # Явно указываем features
monero-rpc = { workspace = true }