[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
# Monero
monero-rpc = "0.8"
# Bitcoin
bitcoin = { version = "0.30", features = ["use-serde"] }

# Общие зависимости
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
hex = "0.4"